// <auto-generated />
using System;
using Datalayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Datalayer.Migrations
{
    [DbContext(typeof(EfstoreContext))]
    [Migration("20190401100038_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebstoreConsole.Datalayer.Orders", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("UserId");

                    b.Property<DateTime>("dateoforder");

                    b.Property<string>("status");

                    b.HasKey("OrderId")
                        .HasName("OrderId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("WebstoreConsole.Entities.Productinfo", b =>
                {
                    b.Property<int>("productinfoID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Brand");

                    b.Property<string>("Color");

                    b.Property<string>("size");

                    b.HasKey("productinfoID")
                        .HasName("productinfoID");

                    b.ToTable("Prodinfo");
                });

            modelBuilder.Entity("WebstoreConsole.Entities.Products", b =>
                {
                    b.Property<int>("ClothingID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.Property<string>("name");

                    b.Property<int>("price");

                    b.Property<string>("status");

                    b.HasKey("ClothingID")
                        .HasName("ClothingID");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("WebstoreConsole.Entities.Shopbasket", b =>
                {
                    b.Property<int>("Checkout_id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ClothingID");

                    b.Property<string>("Name");

                    b.Property<string>("OrderLines");

                    b.Property<int>("Product_id");

                    b.Property<int>("Quantity");

                    b.HasKey("Checkout_id")
                        .HasName("Checkout_id");

                    b.ToTable("shopbaskets");
                });

            modelBuilder.Entity("WebstoreConsole.Entities.Userinformation", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address");

                    b.Property<int>("CountryCode");

                    b.Property<string>("city");

                    b.Property<DateTime>("dateofbirth");

                    b.Property<string>("email");

                    b.Property<string>("fullname");

                    b.Property<string>("gender");

                    b.Property<string>("paymentO");

                    b.HasKey("id")
                        .HasName("id");

                    b.ToTable("userinformtation");

                    b.HasData(
                        new
                        {
                            id = 1,
                            Address = "petersvej 1",
                            CountryCode = 7600,
                            city = "petersborg",
                            dateofbirth = new DateTime(2019, 4, 1, 12, 0, 37, 907, DateTimeKind.Local).AddTicks(1970),
                            email = "Peter@gmail.com",
                            fullname = "peter petersen",
                            paymentO = "MasterCard"
                        },
                        new
                        {
                            id = 2,
                            Address = "AndersVej  1",
                            CountryCode = 7600,
                            city = "Andersborg",
                            dateofbirth = new DateTime(2019, 4, 1, 12, 0, 37, 909, DateTimeKind.Local).AddTicks(9753),
                            email = "anders@gmail.com",
                            fullname = "Anders Andersen",
                            paymentO = "MasterCard"
                        },
                        new
                        {
                            id = 3,
                            Address = "kathrinevej  1",
                            CountryCode = 7600,
                            city = "kathrinebjerg",
                            dateofbirth = new DateTime(2019, 4, 1, 12, 0, 37, 910, DateTimeKind.Local).AddTicks(1792),
                            email = "Kathrine@gmail.com",
                            fullname = "Kathrine Kristiansen",
                            paymentO = "MasterCard"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
